# -*- coding: utf-8 -*-
"""
Main entry point for the CO2 emission prediction benchmark.

Pipeline
--------
1. Load pre-split train/test CSVs (generated by preprocess.py).
2. Apply the variable whitelist defined in config.py.
3. Run feature selection (MI / RF / Pearson / none).
4. Train each registered model with 5-fold cross-validated grid search.
5. Evaluate on the test set and optionally run bootstrap uncertainty analysis.

All results are written to ``data/predict/``.
"""

import os
import pandas as pd

import config
from src.data import load_train_test
from src.features import select_features
from src.models import MODELS
from src.training import run_single_model_task


def main():
    print(f"Working directory : {config.BASE_DIR}")
    print(f"Data directory    : {config.DATA_DIR}")
    print(f"Output directory  : {config.OUTPUT_ROOT}")
    os.makedirs(config.OUTPUT_ROOT, exist_ok=True)

    for scale in config.SCALES:
        train_csv = os.path.join(config.DATA_DIR, f"merged_{scale}_train.csv")
        test_csv  = os.path.join(config.DATA_DIR, f"merged_{scale}_test.csv")

        if not os.path.exists(train_csv) or not os.path.exists(test_csv):
            print(f"[SKIP] Files not found for scale='{scale}': {train_csv}")
            continue

        for method in config.FEATURE_METHODS:
            for k in config.SELECT_K_LIST:
                combo_tag = f"{scale}_{method or 'none'}_{k}"
                print(f"\n{'='*60}")
                print(f" Scale={scale} | Feature method={method} | K={k}")
                print(f"{'='*60}")

                # ── Load data ─────────────────────────────────────────────
                df_tr, df_te = load_train_test(train_csv, test_csv)

                # Extract ID columns before feature filtering
                uids  = df_te["uid"].values  if "uid"  in df_te.columns else None
                years = df_te["year"].values if "year" in df_te.columns else None

                # ── Apply variable whitelist ──────────────────────────────
                if config.SELECTED_FEATURES:
                    keep = list(config.SELECTED_FEATURES)
                    if config.TARGET_COL not in keep:
                        keep.append(config.TARGET_COL)
                    keep = [c for c in keep if c in df_tr.columns]
                    df_tr = df_tr[keep]
                    df_te = df_te[keep]
                    print(f"Whitelist applied: {len(df_tr.columns)} columns "
                          f"(including target)")

                # ── Feature selection ─────────────────────────────────────
                X_tr, X_te, feat_names = select_features(
                    df_tr, df_te, config.TARGET_COL, method=method, k=k)
                y_tr = df_tr[config.TARGET_COL].values
                y_te = df_te[config.TARGET_COL].values

                print(f"Selected features : {len(feat_names)}")
                print(f"Train samples     : {len(y_tr)}")
                print(f"Test  samples     : {len(y_te)}")

                # ── Train each model ──────────────────────────────────────
                combo_out = os.path.join(config.OUTPUT_ROOT, combo_tag)
                for model_name, train_fn in MODELS.items():
                    run_single_model_task(
                        name=model_name,
                        train_fn=train_fn,
                        X_tr=X_tr, y_tr=y_tr,
                        X_te=X_te, y_te=y_te,
                        out_root=combo_out,
                        k_folds=config.K_FOLDS,
                        do_uncertainty=config.DO_UNCERTAINTY,
                        feature_method=method,
                        n_features=len(feat_names),
                        scale=scale,
                        ids=uids,
                        years=years,
                        n_bootstrap=config.N_BOOTSTRAP,
                    )

                print(f"\n[DONE] {combo_tag}")

    print("\nAll tasks completed.")


if __name__ == "__main__":
    main()
